### ISSUE TITLE
유용한 폰트적용 사이트

### ISSUE THREAD

**Issue by leejanghe** [leejanghe/My_Website#11]
## 유용한 폰트 사이트 및 적용법

구글 웹폰트도 좋은데 개인적으로 눈누폰트 사이트 너무 좋은 것 같다! 생각보다 이쁜 폰트가 많아서 자주 사용해야 겠다!

<br />

### 적용법

```css
@font-face {
    font-family: 'KOTRAHOPE';
    src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2110@1.0/KOTRAHOPE.woff2') format('woff2');
    font-weight: normal;
    font-style: normal;
  }

.App{
    font-family: 'KOTRAHOPE';
}
```
[https://noonnu.cc/](https://noonnu.cc/)
